/* This file is autogenerated, do not edit*/
#include "moc_JVBot.cpp"
#include "moc_JVBotDemo.cpp"
#include "moc_JVBotManager.cpp"
#include "moc_JVBotServer.cpp"
#include "moc_JVBotServerUI.cpp"
#include "moc_JVRenderArea.cpp"
